# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html#packages for options

version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - gfortran
    - pandoc  # Required for nbsphinx notebook conversion
  tools:
    python: '3.12'

formats:
  - pdf
  - epub

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-doc.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
