# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html#packages for options

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs