# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html#packages for options

version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - gfortran
  tools:
    python: "3.12"

formats:
  - pdf
  - epub

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: wheel
    - method: pip
      path: numpy
    - method: pip
      path: .
      extra_requirements:
        - docs
