"""
This type stub file was generated by pyright.
"""

"""
**conphas.py**

Provides a native python version of the conphas (phsh3) FORTRAN program
by W. Moritz, which is distributed as part of the SATLEED code
(see "Barbieri/Van Hove phase shift calculation package" section) and can
be found at: http://www.icts.hkbu.edu.hk/surfstructinfo/SurfStrucInfo_files/
leed/leedpack.html

The Conphas() class also provides a number of convenience functions (see
docstrings below).

Examples
--------
>>> from os.path import join
>>> from phaseshifts.conphas import Conphas
>>> con = Conphas(output_file=join('testing', 'leedph_py.d'), lmax=10)
>>> con.set_input_files([join('testing', 'ph1')])
>>> con.set_format('cleed')
>>> con.calculate()

"""
HARTREE = ...
VERBOSE = ...
class Conphas:
    """Class Conphas

    Description
    -----------
    Generates continuous phase shifts (as a function of energy)
    from phases with discontinuities (jumps UM +/- PI). It reformats
    scattered phases and energies to use as input datasets for LEED programs.

    Notes
    -----
    This work is based on the original conphas (phsh3) FORTRAN program by
    W. Moritz, which is distributed as part of the SATLEED code (see
    "Barbieri/Van Hove phase shift calculation package" section) and can be
    found at: http://www.icts.hkbu.edu.hk/surfstructinfo/SurfStrucInfo_files/
    leed/leedpack.html

    """
    def __init__(self, input_files=..., output_file=..., formatting=..., lmax=..., **kwargs) -> None:
        """
        Parameters
        ----------
        input_files : list(str)
            a list of the input files (default None)
        output_file : str
            output filepath - this file will have all pi/2 jumps
            removed to form continuous phase shifts
        lmax (optional) : int
            Maximum angular momentum quantum number to calculate and
            must be in the range 0 <= lmax <= 18 .
        formatting (optional) : str
            output style - use either 'CLEED' or None (default None)

        """
        ...
    
    def read_datafile(self, filename): # -> None:
        """
        Read in discontinuous phase shift file

        Parameters
        ----------
        filename : str
            The path to the discontinuous phase shift file

        """
        ...
    
    def load_data(self, filename): # -> tuple[float | int, float | int, float | int, float | int, list[float]]:
        """
        Load (discontinuous) phase shift data from file

        Parameters
        ----------
        file : str
           Path to phase shift file.

        Returns
        -------
        tuple: (double, double, int, int, ndarray)
           (initial_energy, energy_step, n_phases, lmf, data)

        Notes
        -----
        + `initial_energy` is the starting energy of the phase shifts.
        + `energy_step` is the change in energy between consecutive values.
        + `n_phases` is the number of phase shifts contained in the file.
        + `lmf` is the maximum azimuthal quantum number considered.
        + `data` is a (2 x n_phases) array containing the phase shift data.

        """
        ...
    
    @staticmethod
    def split_phasout(filename, output_filenames=...): # -> list[Any] | list[str]:
        """split phasout input file into separate files"""
        ...
    
    def set_input_files(self, input_files=...): # -> None:
        """set list of input filenames"""
        ...
    
    def set_output_file(self, output_file): # -> None:
        """set output filename"""
        ...
    
    def set_lmax(self, lmax): # -> None:
        """
        Set max orbital angular momentum (azimuthal quantum number)

        Parameters
        ----------
        lmax : int
            Maximum azimuthal quantum number to be considered in calculations.

        """
        ...
    
    def set_format(self, formatting=...): # -> None:
        """
        Set appropriate format from available options

        Parameters
        ----------
        format : str, optional
            The format identifier for different packages; can be 'cleed'
            or None.

        """
        ...
    
    def calculate(self): # -> None:
        """
        Calculates continuous phase shifts from input file(s).

        Examples
        --------
        >>> con = Conphas(output_file=r'testing/leedph_py.d', lmax=10)
        >>> con.set_input_files([r'testing/ph1'])
        >>> con.set_format('cleed')
        >>> con.calculate()
         L = 0
         jump between 25.0 eV and 30.0 eV; IFAK = -1
         L = 1
         jump between 65.0 eV and 70.0 eV; IFAK = -1
         L = 2
         jump between 20.0 eV and 25.0 eV; IFAK = 1
         jump between 80.0 eV and 85.0 eV; IFAK = 0
         L = 3
         L = 4
         jump between 275.0 eV and 280.0 eV; IFAK = 1
         L = 5
         L = 6
         L = 7
         L = 8
         L = 9
         L = 10

        """
        ...
    


