"""
This type stub file was generated by pyright and refined.
"""

from typing import Any, Callable, Dict, Iterator, List, Tuple, Union, Mapping, Optional

class lazyattr:
    """Lazy object attribute whose value is computed on first access."""

    __slots__ = ...
    def __init__(self, func: Callable[..., Any]) -> None: ...
    def __get__(self, instance: Any, owner: Any) -> Any: ...

class Element:
    """Chemical element."""

    number: int
    symbol: str
    name: str
    group: int
    period: int
    block: int
    series: int
    protons: int
    neutrons: int
    nominalmass: int
    electrons: int
    mass: float
    exactmass: float
    eleneg: float
    covrad: float
    atmrad: float
    vdwrad: float
    tboil: float
    tmelt: float
    density: float
    oxistates: str
    eleaffin: float
    eleconfig: str
    eleconfig_dict: Dict[Tuple[int, str], int]
    eleshells: Tuple[int, ...]
    ionenergy: Tuple[float, ...]
    isotopes: Dict[int, Isotope]

    def __init__(self, number: int, symbol: str, name: str, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @lazyattr
    def description(self) -> str:
        """Return text description of element."""
        ...

    def validate(self) -> None:
        """Check consistency of data. Raise Error on failure."""
        ...

class Isotope:
    """Isotope massnumber, relative atomic mass, and abundance."""

    __slots__ = ...
    mass: float
    abundance: float
    massnumber: int
    def __init__(
        self, mass: float = ..., abundance: float = ..., massnumber: Optional[int] = ...
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ElementsDict(Mapping[Union[int, str], Element]):
    """Ordered dict of Elements with lookup by number, symbol, and name."""

    def __init__(self, *elements: Element) -> None: ...
    def __str__(self) -> str: ...
    def __contains__(self, item: object) -> bool: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, str]) -> Element: ...

ELEMENTS: ElementsDict
PERIODS: Dict[int, str]
BLOCKS: Dict[int, str]
GROUPS: Dict[int, str]
SERIES: Dict[int, str]

def sqlite_script() -> str:
    """Return SQL script to create sqlite database of elements."""
    ...

def word_wrap(
    text: str, linelen: int = ..., indent: int = ..., joinstr: str = ...
) -> str:
    """Return string, word wrapped at linelen."""
    ...
