"""
This type stub file was generated by pyright.
"""

"""
Provides CLEED validator and Converter classes.

The CLEED_validator() class provides a method for checking
the input files for errors, whereas the Converter.import_CLEED()
method allows importing CLEED input files as a MTZ_model class

"""
class CLEED_validator:
    """
    Class for validation of CLEED input files
    """
    @staticmethod
    def is_CLEED_file(filename): # -> bool:
        """
        Determine if file is a CLEED input file

        Returns
        -------
        True
            if a valid filename ending in any of .bul, .inp, .bsr, .bmin

        False
            otherwise
        """
        ...
    
    def validate(self, filename, aoi=...):
        r"""
        Checks CLEED input file for errors

        Parameters
        ----------
        filename : str
            Path to input file. Should be \*.bul , \*.ctr, \*.inp or \*.bmin
        aoi : bool
            Check for angle of incidence parameters

        """
        ...
    


class Converter:
    """
    Convert different input into phaseshift compatible input

    """
    @staticmethod
    def import_CLEED(filename, **kwargs):
        """
        Imports CLEED input file and converts model to muffin-tin input.

        It assumes the following:
          * the basis vectors :math:`a_1`, :math:`a_2`, & :math:`a_3` are
            :math:`x`,:math:`y`,:math:`z` cartezian coordinates
          * if no :math:`a_3` is found, the maximum :math:`z` distance between
            atoms multiplied by four is given.
          * the unitcell is converted from cartezian to fractional coordinates
          * atom sites are converted from Angstrom to Bohr units
          * additional info from the phase shift filename is provided by
            splitting the '_' chars:

            1. First string segment is element or symbol, e.g. Ni
            2. Second string segment is the oxidation (valence), e.g. +2

          * lines with :code:`rm:` provide the radii dictionary of the
            individual phase shifts, whereas lines starting with
            :code:`lmax:` provide the lmax dictionary for individual phase
            shifts. Additionally, the valency can be given in lines
            starting with :code:`ox:`. Both bulk and surface input files
            will be searched for these.
          * if no :code:`rm:` found for that species, the atomic radius is used
            for zero valence, otherwise the covalent radius is used.
          * if no lmax values are found for the specific phase shift, then the
            global value will be used instead.
          * if no valence values are found for the specific phase shift, then
            the guessed oxidation value from the phase shift filename is used
            instead. However, if the oxidation state cannot be parsed using
            the filename then a default oxidation state of zero is used.

        Additional information can, however, be provided using 'phs:' at the
        start of a line within the input file and may have the following
        formats:

          1. "**phs:** c *<float>* nh *<int>* nform *<int>* exchange *<float>*"
          2. "**phs:** *<phase_shift>* valence *<float>* radius *<float>*"

        The identifiers ``exchange``, ``nform``, ``valence`` and ``radius`` may
        be abbreviated to ``exc``, ``nf``, ``val`` and ``rad``, respectively.

        Information given in this manner overrides any other input.


        Parameters
        ----------
        filename : str
            Path to input file.

        Returns
        -------
        phaseshifts.model.MTZ_model

        Raises
        ------
        IOError : filename invalid
        ValueError : bad formatting of input

        """
        ...
    


class CSearch:
    """class for csearch related data exchange"""
    def __init__(self, model_name, leed_command=...) -> None:
        ...
    
    def setModel(self, name): # -> None:
        """sets the model name"""
        ...
    
    def getIteration(self, iteration): # -> str | None:
        ...
    
    def getRFactor(self, iteration): # -> None:
        ...
    
    def getTimeStamp(self, iteration): # -> None:
        ...
    


