"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Set, Union

"""
**model.py**

Provides convenience functions for generating input and calculating
atomic charge densities for use with the Barbieri/Van Hove phase
shift calculation package.

"""

class Atom:
    """
    Atom class for input into cluster model for muffin-tin potential
    calculations.
    """

    element: str
    symbol: str
    name: str
    coordinates: List[float]
    tag: str
    radius: float
    valence: int
    occupancy: float
    lmax: int

    def __init__(
        self,
        element: Union[str, int],
        coordinates: Optional[List[float]] = ...,
        **kwargs: Any
    ) -> None:
        """
        Constructor for Atom class.

        Parameters
        ----------

        element : str or int
            This is either the elemental symbol, name or atomic number.
        coordinates : list[float, float, float] or ndarray
            The fractional coordinates within the unitcell in terms of the
            basis vector a.
        tag : str, optional
            Add a name tag to this element (useful if dealing with multiple
            atoms of the same element in a given model). Default is the
            symbol for that element - numeric ids may be appended in the model
            class.
        radius : float, optional
            The muffin-tin radius of the atom in Angstroms (default is to
            lookup 'atmrad' in the element dictionary).
        valence : int, optional
            The valency of the atom (default is to assume neutral atom).
        occupancy : float, optional
            The fractional occupancy of the atom in the given site.

        """
        ...

    def __eq__(self, other) -> bool: ...
    def __neq__(self, other):  # -> bool:
        ...

    def __repr__(self):  # -> str:
        ...

    def __hash__(self) -> int: ...
    def set_coordinates(self, coordinates):  # -> None:
        ...

    def set_valence(self, valency):  # -> None:
        """Sets the valency of the atom"""
        ...

    def set_mufftin_radius(self, radius):  # -> None:
        """
        Sets the muffin-tin radius of the atom in Angstroms.
        """
        ...

class Unitcell:
    """
    Unitcell class
    """

    a: float
    c: float
    alpha: float
    beta: float
    gamma: float
    basis: Any
    _a: float
    _c: float

    def __init__(self, a: float, c: float, matrix_3x3: Any, **kwargs: Any) -> None:
        """
        Constructor for the Unitcell class

        Parameters
        ----------
        a : float
            The in-plane lattice vector in Angstroms
        c : float
            The out-of-plane lattice vector in Angstroms. For cubic systems this
            will be equal to a.
        matrix_3x3: ndarray
            A 3x3 matrix describing the x,y,z construction of a,b,c basis vectors
            of the unitcell. Units for x, y & z should be in terms of fractional
            coordinates.
        alpha : float, optional
            Angle alpha in degrees.
        beta : float, optional
            Angle beta in degrees.
        gamma : float, optional
            Angle gamma in degrees.

        """
        ...

    def __eq__(self, other) -> bool: ...
    def __neq__(self, other):  # -> bool:
        ...

    def __repr__(self):  # -> str:
        ...

    def __hash__(self) -> int: ...
    def set_vectors(self, m3x3):  # -> None:
        ...

    def set_a(self, a):  # -> None:
        """
        Description
        -----------
        Set the magnitude of the in-plane lattice vector a in Angstroms.

        Parameters
        ----------
        a: float
            The magnitude of the in-plane lattice vector in Angstroms

        Notes
        -----
        To retrieve a in terms of Angstroms use 'unitcell.a', whereas the
        internal parameter 'unitcell._a' converts a into Bohr radii
        (1 Bohr = 0.529Å), which is used for the muffin-tin potential
        calculations in libphsh (CAVPOT subroutine).

        """
        ...

    def set_c(self, c):  # -> None:
        """
        Description
        -----------
        Set the magnitude of the out-of-plane lattice vector a.

        Parameters
        ----------
        c : float
            The magnitude of the in-plane lattice vector in Angstroms

        Notes
        -----
        To retrieve c in terms of Angstroms use 'unitcell.c', whereas the
        internal parameter 'unitcell._c' converts c into Bohr radii
        (1 Bohr = 0.529Å), which is used for the muffin-tin potential
        calculations in libphsh (CAVPOT subroutine).

        """
        ...

    def set_alpha(self, alpha):  # -> None:
        ...

    def set_beta(self, beta):  # -> None:
        ...

    def set_gamma(self, gamma):  # -> None:
        ...

class CoordinatesError(Exception):
    """Coordinate exception to raise and log duplicate coordinates."""

    def __init__(self, msg) -> None: ...
    def __str__(self) -> str: ...
    def __unicode__(self):  # -> str:
        ...

class Model:
    """
    Generic model class.
    """

    atoms: List[Atom]
    name: str
    unitcell: Unitcell

    def __init__(self, unitcell: Unitcell, atoms: List[Atom], **kwargs: Any) -> None:
        """
        Constructor for Model class.

        Parameters
        ----------
        unitcell : Unitcell
            An instance of the Unitcell class.
        atoms : list
            Array of Atom class instances which constitute the model.

        """
        ...

    def __eq__(self, other) -> bool: ...
    def __neq__(self, other):  # -> bool:
        ...

    def __repr__(self):  # -> str:
        ...

    def __hash__(self) -> int: ...
    def add_atom(self, element, position, **kwargs):  # -> None:
        """
        Append an Atom instance to the model

        Parameters
        ----------
        element : str or int
            Either an element name, symbol or atomic number.
        position : list(float) or ndarray
            (1x3) array of the fractional coordinates of the atom
            within the unit cell in terms of the lattice vector a.

        """
        ...

    def check_coordinates(self):  # -> None:
        """
        Check for duplicate coordinates of different atoms in model.

        Raises
        ------
        CoordinateError : exception
          If duplicate positions found.

        """
        ...

    @property
    def elements(self) -> Set[Any]:
        ...

    def set_atoms(self, atoms):  # -> None:
        """
        Set the atoms for the model.

        Parameters
        ----------
        atoms : list(Atoms)
            Array of Atom instances. Entries in the list which are
            not of type Atom will be ignored.

        Raises
        ------
        TypeError : exception
          If atoms parameter is not a list.

        """
        ...

    def set_unitcell(self, unitcell):  # -> None:
        """
        Set the unitcell for the model

        Parameters
        ----------
        unitcell : Unitcell
            Instance of Unitcell class to set to model.

        Raises
        ------
        TypeError : exception
          If unitcell parameter is not a Unitcell.

        """
        ...

class MTZ_model(Model):
    """
    Muffin-tin potential Model subclass for producing input file
    for muffin-tin calculations in the Barbieri/Van Hove phase
    shift calculation package.
    """

    nh: int
    exchange: float
    nform: int
    mtz: Optional[Any]
    header: str
    coordinates: List[Any]

    def __init__(self, unitcell: Unitcell, atoms: List[Atom], **kwargs: Any) -> None:
        """
        Constructor for Model class.

        Parameters
        ----------
        unitcell : Unitcell
            An instance of the Unitcell class.
        atoms : list
            Array of Atom class instances which constitute the model.
        nh : int, optional
            Parameter for estimating the muffin-tin zero (default: 10).
        exchange : float, optional
            Hartree type exchange term alpha (default: 0.7200).
        c : float, optional
            The height of the slab in Angstroms - if this is much larger
            than the bulk c distance then there will be a large vacuum
            and therefore should be used when calculating a thin slab
            rather than a bulk muffin-tin potential. Default is to lookup
            the out-of-plane basis vector bulk value.
        nform : int or str, optional
            The phase shift calculation type, which can be 0 or 'cav' for
            using the cavpot subroutine, 1 or 'wil' for using the William's
            method, and 2 or 'rel' for using relativistic calculations suitable
            for the CLEED package.

        """
        ...

    def set_nh(self, nh):  # -> None:
        """Sets the nh muffin-tin zero estimation parameter"""
        ...

    def set_exchange(self, alpha):  # -> None:
        """Sets the alpha exchange term for muffin-tin calculation"""
        ...

    def set_nform(self, nform):
        """
        Sets form of muffin-tin calculation

        Parameters
        ----------
        nform : int or str
          This governs the type of calculation, where nform can be:

          **1.** "cav" or 0 - use Cavendish method

          **2.** "wil" or 1 - use William's method

          **3.** "rel" or 2 - Relativistic calculations

        """
        ...

    def set_slab_c(self, c):  # -> None:
        """
        Description
        -----------
        Set the maximum height of the slab in Angstroms - if this is
        much larger than the bulk c distance then there will be a large
        vacuum and therefore should be used when calculating a thin slab
        rather than a bulk muffin-tin potential.

        Examples
        --------
        For Re the bulk c distance is 2.76Å, whereas a possible slab c distance
        could be ~10Å.

        """
        ...

    def load_from_file(self, filename):  # -> None:
        """
        Description
        -----------
        Load an cluster/slab input file and update the class instance variables

        Parameters
        ----------
        filename : str
            The path of the input file (e.g. cluster*.i or *slab*.i)

        Raises
        ------
        IOError : exception
          If the file cannot be read.
        TypeError : exception
          If a input line cannot be parsed correctly.

        """
        ...

    def create_atorbs(self, **kwargs):  # -> dict[str, list[Any]]:
        """
        Description
        -----------
        Create Atorb input files for each element in model.

        Arguments
        ---------
        output_dir : str
            Path to output directory for files
        library_dir : str
            Path to library of input files. Use this if you've previously
            created input files for a given element as it doesn't need to
            recalculate the radial charge density every time - note this
            is also a workaround to allow precalculated files if your machine's
            output is drastically different from what is expected.
        config : dict
            See help(atorb.gen_input) for list of keywords and values.

        Returns
        -------
        output_files : dict
            Dictionary list of atorb*.i input files for the Atorb class to
            calculate the charge density from.

        """
        ...

    def gen_atomic(self, **kwargs):  # -> str:
        """
        Description
        -----------

        Create atomic*.i input file for MTZ input based on model or
        list of files.

        Parameters
        ----------
        input_dir : str
            Input directory where at*.i files are kept.
        input_files : tuple
            List of input files to generate atomic input file from.
        output_file : str
            The filename of the resulting atomic*.i output file, which is
            simply a superimposed set of the radial charge densities from
            the individual input files.

        Returns
        -------
        output_file : str
            Returns the output file path string.

        Raises
        ------
        IOError : exception
            If either input directory or files do not exist.

        Notes
        -----
        If 'input_files' is not given then the default list of input files are
        inferred from the list of atoms in the model.

        """
        ...

    def get_MTZ(self, filename):  # -> None:
        """Retrieves muffin-tin potential from file"""
        ...

    def calculate_MTZ(self, mtz_string=..., **kwargs) -> str:
        """
        Description
        -----------
        Calculate the muffin-tin potential (MTZ) for a given cluster file

        Parameters
        ----------
        atomic_file : str
            The path to the atomic input file. If this is omitted the default
            is generate one using the MTZ_model.gen_atomic() method.
        cluster_file : str
            The path to the cluster input file which may be a bulk or slab
            model.
        slab : int or bool
            Determines whether the MTZ calculation is for a slab model (True).
            The default is a bulk calculation.
        output : dict
            Dictionary output of 'mtz' - muffin-tin potential & 'output_file'
            - the path to the MTZ output file.


        Returns
        -------
        output_files : list(str)
            Paths to the MTZ output file.

        """
        ...

    def gen_input(self, **kwargs):  # -> None:
        """
        Description
        -----------
        Generate input file for use in the Barbieri/Van Hove phase shift
        calculation package (phsh1 or libphsh)

        Arguments
        ---------
        bulk : bool
            If True the c value is set to the bulk value...
        filename : str
            The path of the generated file (e.g. 'cluster.i')
        header : str
            A file header string.
        bulk : bool
            Specify whether generated file is a bulk or slab model
        pos_check : bool
            If true, the positions of each atom will be checked and
            any duplicates will cause a CoordinateError to be raised.
        nform : int or str
            Choose calculation type from either:
              - Cavendish (0)
              - Williams (1)
              - Relativistic (2)
        exchange : float
            Hartree-Fock exchange term alpha.
        nh : int
            Term used to estimate the muffin-tin zero.

        Returns
        -------
        filename on success

        Raises
        ------
        CoordinatesError : exception
          if the model atoms have duplicate coordinates and the 'pos_check'
          kwarg is set to True.

        """
        ...

    def get_elements(self):  # -> set[Any]:
        """Return the unique elements in model"""
        ...
