"""
This type stub file was generated by pyright.
"""

import argparse

__doc__ = ...

def required_length(nmin, nmax):  # -> type[RequiredLength]:
    """custom action to check range"""

    class RequiredLength(argparse.Action): ...

class Wrapper:
    """Class for automating the Barbieri/Van Hove phase shift calculation workflow.

    This class provides methods to generate phase shift files from atomic and cluster input data,
    handling all intermediate steps: atomic charge density, muffin-tin potential, phase shift calculation,
    phase-jump removal, and output formatting. It supports both Python and Fortran backends, and is
    compatible with SATLEED and CLEED file formats.

    Scientific Rationale
    -------------------
    Automating the workflow ensures reproducibility and correct sequencing of physical and computational steps,
    as required for LEED surface structure analysis.

    References
    ----------
    - `Barbieri, G., & Van Hove, M. A. (1979). "Phase shift calculation package for LEED." Surf. Sci. 90, 1-25.
     <https://doi.org/10.1016/0039-6028(79)90470-7>`_
    - Moritz, W. (SATLEED code): http://www.icts.hkbu.edu.hk/surfstructinfo/SurfStrucInfo_files/leed/leedpack.html
    - See also: https://phaseshifts.readthedocs.io/en/latest/phshift2007.html

    """

    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def autogen_from_input(bulk_file, slab_file, tmp_dir=..., model_name=..., **kwargs):
        """
           Generate phase shifts from slab/cluster and bulk input files, following the Barbieri/Van Hove workflow.

           This method automates the full sequence described in:
           - `Barbieri, G., & Van Hove, M. A. (1979). "Phase shift calculation package for LEED." Surf. Sci. 90, 1-25.
        <https://doi.org/10.1016/0039-6028(79)90470-7>`_
           - Moritz, W. (SATLEED code): http://www.icts.hkbu.edu.hk/surfstructinfo/SurfStrucInfo_files/leed/leedpack.html
           - See also: https://phaseshifts.readthedocs.io/en/latest/phshift2007.html

           Steps:
           1. Atomic charge density calculation (Dirac-Fock/Hartree-Fock)
           2. Muffin-tin potential generation
           3. Phase shift calculation (relativistic/non-relativistic)
           4. Removal of phase discontinuities (pi-jumps)
           5. Output formatting for LEED analysis

           Parameters
           ----------
           bulk_file : str
               Path to the bulk MTZ or CLEED input file.
           slab_file : str
               Path to the slab/cluster MTZ or CLEED input file.
           tmp_dir : str, optional
               Temporary directory for intermediate files.
           model_name : str, optional
               Name of the model.
           store : bool or str, optional
               Whether to keep generated files and where to store them.
           format : str, optional
               Output format for phase shift files ('cleed', 'curve', etc.).
           range : tuple(float, float, float), optional
               Energy range for phase shift calculation (start, stop, step in eV).

           Returns
           -------
           output_files : list of str
               List of generated phase shift output filenames.

           Scientific Context
           ------------------
           This workflow implements the full Barbieri/Van Hove methodology for LEED phase shift generation,
           ensuring all physical and computational steps are performed in the correct order. For further details,
           see the references above and the user guide at https://phaseshifts.readthedocs.io/en/latest/phshift2007.html

        """
        ...

class CLIError(Exception):
    """Generic exception to raise and log different fatal errors."""

    def __init__(self, msg) -> None: ...
    def __str__(self) -> str: ...
    def __unicode__(self):  # -> str:
        ...

def main(argv=...):  # -> Literal[0, 2] | None:
    """
    Main command-line interface for phase shift generation.

    Parses user arguments, sets up the workflow, and executes the full Barbieri/Van Hove phase shift
    calculation sequence. Supports options for input files, output formatting, energy range, and
    intermediate file management.

    Parameters
    ----------
    argv : list of str, optional
        Command-line arguments (default: sys.argv).

    Returns
    -------
    int
        Exit code (0 for success).

    Scientific Context
    ------------------
    This CLI enables reproducible, automated phase shift generation for LEED analysis, following
    best practices in surface science computation.

    References
    ----------
    - `Barbieri, G., & Van Hove, M. A. (1979). "Phase shift calculation package for LEED." Surf. Sci. 90, 1-25.
     <https://doi.org/10.1016/0039-6028(79)90470-7>`_
    - Moritz, W. (SATLEED code): http://www.icts.hkbu.edu.hk/surfstructinfo/SurfStrucInfo_files/leed/leedpack.html
    - See also: https://phaseshifts.readthedocs.io/en/latest/phshift2007.html

    """
    ...

if __name__ == "__main__":
    ...
