"""
This type stub file was generated by pyright and refined.
"""

import argparse
from typing import List, Optional

"""A collection of utilities to assist with extracting phshift2007 in a cross-platform manner."""
PHSHIFT2007_DOWNLOAD_URL: str
DEFAULT_DIRPATH: str
WINDOWS_INCOMPATIBLE_FLAGS: List[str]
COMPILER_FLAGS: List[str]

def download_phshift2007(dirpath: str = ...) -> str:
    """Download phshift2007 from the web."""
    ...

def unzip_phshift2007(zipfile_path: str, dirpath: str = ...) -> None:
    """Unzip phshift2007 contents from the zipfile."""
    ...

def extract_phshift2007(dirpath: str = ...) -> None:
    """Extracts the phshift2007 Fortran programs from the phshift2007.zip archive."""
    ...

def compile_phshift2007(dirpath: str = ...) -> None:
    """Compiles the phshift2007 Fortran programs."""
    ...

def do_action(action: str, output_dirpath: str = ...) -> None:
    """Perform the specified action."""
    ...

def get_parser() -> argparse.ArgumentParser:
    """Get the parser object for the script."""
    ...

def main(argv: Optional[List[str]] = ...) -> None:
    """Main entry point for the script."""
    ...
