"""
This type stub file was generated by pyright.
"""

"""Module for phaseshifts config and settings, typically defined by environment variables.

Notes
-----
Environment variables will be prefixed with :code:`PHASESHIFTS_` to namespace them and
avoid conflicts with other packages.

"""
def load_bool_env_var(var_name: str, default: str = ...) -> bool:
    """Load boolean value from environment variable.

    Parameters
    ----------
    env_var : str
        Environment variable name.
    default : str
        The default value if environment variable is not set.

    Returns
    -------
    bool
        Boolean value of environment variable.

    """
    ...

_READTHEDOCS = ...
_compile_default = ...
COMPILE_MISSING = ...
DEBUG = ...
TESTRUN = ...
PROFILE = ...
