"""
This type stub file was generated by pyright.
"""

from typing import List
from pydantic import BaseModel

"""
Validation helpers for atorb input files.

This module implements a validation layer for the Barbieri/Van Hove 'atorb'
atomic structure code input format. It ensures that the input files—whether
generated by the user or by the high-level Python API—adhere to the strict
formatting and physical constraints required by the underlying Fortran solver.

The validation process acts as a safeguard, catching errors such as invalid
quantum numbers, incorrect grid dimensions, or formatting issues (like
inline comment spacing) that would otherwise cause the legacy Fortran binary
to crash or produce non-physical results.
"""

def coerce_model(model_cls, data):
    """Helper to support pydantic v1/v2 or fallback shim."""
    ...

class AtorbElectron(BaseModel):
    """
    Representation of a single electron orbital state in the Dirac-Fock model.

    This class models the quantum numbers and occupancy of an atomic orbital,
    strictly enforcing quantum mechanical selection rules.

    Attributes
    ----------
    n : int
        Principal quantum number (:math:`n \\ge 1`). Determines the energy shell.
    l : int
        Azimuthal quantum number (:math:`0 \\le l < n`). Determines orbital angular momentum.
    m : int
        Magnetic quantum number. Typically unused (0) in spherical averages but required by format.
    j : float
        Total angular momentum quantum number (:math:`j = l \\pm 1/2`).
        Must be a half-integer.
    s : int
        Spin multiplicity/context flag. Typically 1.
    occ : float
        Orbital occupancy number. Can be fractional to represent spherically
        averaged open shells.
    """

    n: int
    l: int
    m: int
    j: float
    s: int
    occ: float
    def ensure_valid(self):  # -> Self:
        """
        Run lightweight semantic checks on quantum numbers.

        Verifies:
        - :math:`n > 0`
        - :math:`0 \\le l < n`
        - :math:`s \\in \\{0, 1\\}`
        - Non-negative occupancy
        - :math:`j` is a half-integer

        Returns
        -------
        AtorbElectron
            The validated instance.

        Raises
        ------
        ValidationError
            If any physical constraint is violated.
        """
        ...

class AtorbInputModel(BaseModel):
    """
    Structured representation of an atorb simulation input file.

    This model encapsulates the global parameters for the atomic structure
    calculation (such as grid definition and exchange-correlation method)
    and the list of electronic orbitals.

    Attributes
    ----------
    z : int
        Atomic number (proton count) of the element.
    nr : int
        Number of points in the logarithmic radial grid.
    rel : int
        Relativistic switch. 1 for relativistic (Dirac), 0 for non-relativistic (Schrödinger).
    method : str
        Exchange-correlation potential approximation code (e.g., '0.d0' for Hartree-Fock,
        '1.d0' for LDA).
    relic : float
        Relic parameter passed to the solver (often 0.0).
    nlevels : int
        Total number of electronic orbitals defined.
    mixing_scf : float
        Mixing parameter for the Self-Consistent Field (SCF) iteration (0.0 < x <= 1.0).
    eigen_tol : float
        Convergence tolerance for orbital eigenvalues (in Hartrees).
    ech : int
        Parameter related to the exchange potential configuration.
    orbitals : List[AtorbElectron]
        List of electron orbitals defining the electronic configuration.
    output : str
        Filename for the resulting charge density output file.
    header : str
        Header/Comment line for the input file.
    """

    z: int
    nr: int
    rel: int
    method: str
    relic: float
    nlevels: int
    mixing_scf: float
    eigen_tol: float
    ech: int
    orbitals: List[AtorbElectron]
    output: str
    header: str = ...
    def ensure_valid(self):  # -> Self:
        """
        Perform semantic validation on the full input model.

        Checks:
        - Positive Z and NR
        - Valid relativistic flag
        - Consistency between `nlevels` and the length of `orbitals`
        - Recursive validation of all `AtorbElectron` instances

        Returns
        -------
        AtorbInputModel
            The validated instance.

        Raises
        ------
        ValidationError
            If configuration is invalid or inconsistent.
        """
        ...

def format_orbital_line(orbital):  # -> str:
    """
    Format a single orbital entry for the input file.

    Parameters
    ----------
    orbital : AtorbElectron
        The orbital data to format.

    Returns
    -------
    str
        A fixed-width/spaced string suitable for Fortran input.
    """
    ...

def validate_atorb_file(filename):  # -> AtorbInputModel:
    """
    Validate an existing atorb input file.

    Parameters
    ----------
    filename : str
        Path to the input file.

    Returns
    -------
    AtorbInputModel
        The validated model containing the file data.

    Raises
    ------
    IOError
        If file does not exist.
    ValueError
        If file content is invalid.
    """
    ...

def render_atorb_file(model, filename, file_handle=None):
    """
    Render a validated AtorbInputModel to a file on disk.

    Generates a properly formatted text file that can be consumed by the
    Fortran 'atorb' solver. Includes standard comments and separators.

    Parameters
    ----------
    model : AtorbInputModel
        The data model to serialize.
    filename : str or file-like
        The destination file path or file-like object.
    file_handle : file-like, optional
        Explicit file handle to write to.

    Returns
    -------
    str
        The path to the generated file.
    """
    ...
