"""
This type stub file was generated by pyright.
"""

import importlib
import importlib.util
import os
import sys
from ._fortran_lib import (
    FORTRAN_LIBS,
    LIBPHSH_MODULE,
    compile_f2py_shared_library,
    find_shared_library_path,
    is_module_importable,
)
from .. import settings

"""The subpackage is for library code, likely compiled from Fortran or C sources."""
if (
    settings.COMPILE_MISSING
    and not os.environ.get("PHASESHIFTS_SKIP_COMPILE_ON_IMPORT")
    and not is_module_importable(LIBPHSH_MODULE)
):
    ...
_WIN_DLL_DIRS = ...
libphsh = ...
