"""
This type stub file was generated by pyright.
"""

"""Compatibility helpers for environments where ``distutils`` is missing."""
def ensure_distutils(): # -> bool:
    """Ensure a ``distutils`` implementation is importable."""
    ...

