"""
This type stub file was generated by pyright.
"""

"""This module can be used for checking whether Fortran wrapped libraries such as `libphsh` hve compiled successfully.

Notes
-----

The functionality currently targets `libphsh.f` by default and provides utilities to check for the
compiled wrapped `libphsh` fortran shared library and adds the ability to crudely compile
on the fly (useful when installing this package from source distribution).
"""
LIBPHSH_MODULE = ...
FORTRAN_LIBS = ...

def find_shared_library_path(module_name):  # -> None:
    """Locate a compiled extension for ``module_name`` across common paths.

    In editable installs the pure-Python package is often imported from the
    source tree while the compiled extension lands in site-packages. The
    standard importer then misses the binary. This helper searches sys.path and
    site-packages for any matching shared object.
    """
    ...

def is_module_importable(module):  # -> bool:
    """Determine whether `module` is importable."""
    ...

def compile_f2py_shared_library(
    source: str,
    module_name: str | None = ...,
    cwd: str | None = ...,
    signature: str | None = ...,
    **f2py_kwargs: str
) -> int:
    """Compile `source` into f2py wrapped shared library given by `module_name`.

    Examples
    --------
    >>> compile_f2py_shared_library(**FORTRAN_LIBS[LIBPHSH_MODULE])

    See Also
    --------
    numpy.f2py
    """
    ...
