"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Tuple

def get_input(prompt: str) -> str: ...

class hartfock(object):
    def __init__(
        self,
        iorbs: int = ...,
        iside: int = ...,
        lmax: int = ...,
        ihmax: int = ...,
        nrmax: int = ...,
        ntmax: int = ...,
        npmax: int = ...,
        input_stream: str = ...,
    ) -> None: ...

def _pseudize_prompt_cutoff(rcut: Optional[float], factor: Optional[float]) -> Tuple[float, float]: ...

def _pseudize_select_cutoff(
    rcut: float,
    phi: List[float],
    r: List[float],
    istop: int,
    n: int,
    l: int,
) -> float: ...

def _pseudize_indices(
    rcut: float,
    rmin: float,
    rmax: float,
    nr: int,
    r: List[float],
    njrc: List[int],
    lp: int,
) -> Tuple[float, int, int, float]: ...

def _pseudize_normalize_phi(phi: List[float], jrt: int) -> None: ...

def _pseudize_integral_norm(phi: List[float], dr: List[float], jrt: int) -> float: ...

def _pseudize_reference_values(
    ev: float,
    l: int,
    xkappa: float,
    n: int,
    jrt: int,
    phi: List[float],
    integ_ctx: Any,
    dr: List[float],
) -> Tuple[float, float, float]: ...

def _pseudize_apply_polynomial_potential(
    v: List[float],
    r: List[float],
    r2: List[float],
    dl: float,
    rcut: float,
    jrc: int,
) -> None: ...

def _pseudize_compute_xi(
    phi0: List[float],
    dr: List[float],
    r: List[float],
    rcut: float,
    factor: float,
    jrt: int,
) -> Tuple[float, float, float]: ...

def _pseudize_compute_deltal(xi0: float, xi1: float, xi2: float, c00: float) -> float: ...

def _pseudize_update_phi(
    phi: List[float],
    phi0: List[float],
    yl: List[float],
    r: List[float],
    rcut: float,
    factor: float,
    deltal: float,
    jrt: int,
) -> None: ...

def _pseudize_update_potential(
    v: List[float],
    vraw: List[float],
    phi: List[float],
    phi0: List[float],
    yl: List[float],
    rf: List[float],
    vf: List[float],
    r: List[float],
    rcut: float,
    factor: float,
    jrt: int,
    fitx0_args: Any,
    integ_args: Any,
) -> float: ...

def _pseudize_iteration(
    phi: List[float],
    phi0: List[float],
    v: List[float],
    vraw: List[float],
    yl: List[float],
    rf: List[float],
    vf: List[float],
    r: List[float],
    dr: List[float],
    rcut: float,
    factor: float,
    jrt: int,
    ev: float,
    l: int,
    xkappa: float,
    n: int,
    integ_ruse_ctx: Any,
    fitx0_args: Any,
    xi0: float,
    xi1: float,
    xi2: float,
    c00: float,
) -> Tuple[float, float]: ...

def pseudize(
    i: int,
    orb: List[List[float]],
    ev: float,
    l: int,
    xj: float,
    n: int,
    njrc: List[int],
    zeff: float,
    v: List[float],
    q0: List[float],
    xm1: List[float],
    xm2: List[float],
    nr: int,
    rmin: float,
    rmax: float,
    r: List[float],
    dr: List[float],
    r2: List[float],
    dl: float,
    rel: float,
    phi: List[float],
    rcut: Optional[float] = ...,
    factor: Optional[float] = ...,
) -> None: ...

def __getattr__(name: str) -> Any: ...
