C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywraphb (hbf2pywrap, x, factor)
      external hb
      double precision x
      double precision factor
      double precision hbf2pywrap, hb
      hbf2pywrap = hb(x, factor)
      end


      subroutine f2pywrapCAVPOT (CAVPOTf2pywrap, MTZ_STRING, SLAB_
     &FLAG, ATOMIC_FILE, CLUSTER_FILE, MUFFTIN_FILE, OUTPUT_FILE, INFO_F
     &ILE)
      external CAVPOT
      integer SLAB_FLAG
      character*(*) MTZ_STRING
      character*(*) ATOMIC_FILE
      character*(*) CLUSTER_FILE
      character*(*) MUFFTIN_FILE
      character*(*) OUTPUT_FILE
      character*(*) INFO_FILE
      real CAVPOTf2pywrap, CAVPOT
      CAVPOTf2pywrap = CAVPOT(MTZ_STRING, SLAB_FLAG, ATOMIC_FILE, 
     &CLUSTER_FILE, MUFFTIN_FILE, OUTPUT_FILE, INFO_FILE)
      end


      subroutine f2pywrapF12 (F12f2pywrap, X, Y, Z, N)
      external F12
      double precision Z
      integer N
      real X(10)
      real Y(10)
      double precision F12f2pywrap, F12
      F12f2pywrap = F12(X, Y, Z, N)
      end


      subroutine f2pywrapF44 (F44f2pywrap, L, X)
      external F44
      integer L
      double precision X
      double precision F44f2pywrap, F44
      F44f2pywrap = F44(L, X)
      end


      subroutine f2pywrapF45 (F45f2pywrap, L, X)
      external F45
      integer L
      double precision X
      double precision F45f2pywrap, F45
      F45f2pywrap = F45(L, X)
      end


      subroutine f2pywrapDLGKAP (DLGKAPf2pywrap, E, KAPPA)
      external DLGKAP
      double precision E
      integer KAPPA
      double precision DLGKAPf2pywrap, DLGKAP
      DLGKAPf2pywrap = DLGKAP(E, KAPPA)
      end


      subroutine f2pyinitWF(setupfunc)
      external setupfunc
      double precision WF2(250,14)
      double precision WC(14)
      integer LC(14)
      common /WF/ WF2,WC,LC
      call setupfunc(WF2,WC,LC)
      end

      subroutine f2pyinitWK(setupfunc)
      external setupfunc
      double precision WK1(250)
      double precision WK2(250)
      common /WK/ WK1,WK2
      call setupfunc(WK1,WK2)
      end

      subroutine f2pyinitCMRV(setupfunc)
      external setupfunc
      double precision R(201)
      double precision V(201,15)
      integer NR
      integer NL
      double precision Z
      common /CMRV/ R,V,NR,NL,Z
      call setupfunc(R,V,NR,NL,Z)
      end

      subroutine f2pyinitCM5(setupfunc)
      external setupfunc
      double precision Y(30,4)
      double precision F(30,4)
      integer ILST
      common /CM5/ Y,F,ILST
      call setupfunc(Y,F,ILST)
      end

      subroutine f2pyinitCM16(setupfunc)
      external setupfunc
      double precision E1
      double precision E2
      integer NE
      integer IX
      integer NEUO
      common /CM16/ E1,E2,NE,IX,NEUO
      call setupfunc(E1,E2,NE,IX,NEUO)
      end

      subroutine f2pyinitZ(setupfunc)
      external setupfunc
      double precision RMAXI
      common /Z/ RMAXI
      call setupfunc(RMAXI)
      end

      subroutine f2pyinitZZZZ(setupfunc)
      external setupfunc
      double precision ZP(340)
      double precision VS
      integer IPT
      integer JRI
      common /ZZZZ/ ZP,VS,IPT,JRI
      call setupfunc(ZP,VS,IPT,JRI)
      end

      subroutine f2pyinitRADFUN(setupfunc)
      external setupfunc
      double precision U(340)
      double precision W(340)
      common /RADFUN/ U,W
      call setupfunc(U,W)
      end


