C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.26.4)
C     It contains Fortran 77 wrappers to fortran functions.
C     NOTE: This generated wrapper is checked in so builds (notably
C     Python 3.8) can use a pre-generated f2py bridge instead of
C     invoking f2py at build time.

      subroutine f2pywraphb (hbf2pywrap, x, factor)
      external hb
      double precision x
      double precision factor
      double precision hbf2pywrap
      double precision  hb
      hbf2pywrap = hb(x, factor)
      end


      subroutine f2pywrapcavpot (cavpotf2pywrap, mtz_string, slab_
     &flag, atomic_file, cluster_file, mufftin_file, output_file, info_f
     &ile)
      external cavpot
      integer slab_flag
      character*(*) mtz_string
      character*(*) atomic_file
      character*(*) cluster_file
      character*(*) mufftin_file
      character*(*) output_file
      character*(*) info_file
      real cavpotf2pywrap
      real  cavpot
      cavpotf2pywrap = cavpot(mtz_string, slab_flag, atomic_file,
     &cluster_file, mufftin_file, output_file, info_file)
      end


      subroutine f2pywrapf12 (f12f2pywrap, x, y, z, n)
      external f12
      real z
      integer n
      real x(10)
      real y(10)
      real f12f2pywrap
      real  f12
      f12f2pywrap = f12(x, y, z, n)
      end


      subroutine f2pywrapf44 (f44f2pywrap, l, x)
      external f44
      integer l
      real x
      real f44f2pywrap
      real  f44
      f44f2pywrap = f44(l, x)
      end


      subroutine f2pywrapf45 (f45f2pywrap, l, x)
      external f45
      integer l
      real x
      real f45f2pywrap
      real  f45
      f45f2pywrap = f45(l, x)
      end


      subroutine f2pywrapdlgkap (dlgkapf2pywrap, e, kappa)
      external dlgkap
      double precision e
      double precision kappa
      double precision dlgkapf2pywrap
      double precision  dlgkap
      dlgkapf2pywrap = dlgkap(e, kappa)
      end


      subroutine f2pyinitwk_cav(setupfunc)
      external setupfunc
      double precision wk1(250)
      double precision wk2(250)
      common /wk_cav/ wk1,wk2
      call setupfunc(wk1,wk2)
      end

      subroutine f2pyinitwf(setupfunc)
      external setupfunc
      double precision wf2(250,14)
      double precision wc(14)
      integer lc(14)
      common /wf/ wf2,wc,lc
      call setupfunc(wf2,wc,lc)
      end

      subroutine f2pyinitwk_cle(setupfunc)
      external setupfunc
      real ex(20)
      real fac(20)
      real fnt(20)
      integer nt(20)
      common /wk_cle/ ex,fac,fnt,nt
      call setupfunc(ex,fac,fnt,nt)
      end

      subroutine f2pyinitwk_hsin(setupfunc)
      external setupfunc
      real rr(250)
      real rs(250)
      common /wk_hsin/ rr,rs
      call setupfunc(rr,rs)
      end

      subroutine f2pyinitwk_mad(setupfunc)
      external setupfunc
      real g(3,3)
      real vmm(5)
      real fr(5)
      real ra(3)
      real ga(3)
      common /wk_mad/ g,vmm,fr,ra,ga
      call setupfunc(g,vmm,fr,ra,ga)
      end

      subroutine f2pyinitwk_mtz(setupfunc)
      external setupfunc
      real x(3)
      real rb(3)
      common /wk_mtz/ x,rb
      call setupfunc(x,rb)
      end

      subroutine f2pyinitwk_nbr(setupfunc)
      external setupfunc
      real rj(3)
      common /wk_nbr/ rj
      call setupfunc(rj)
      end

      subroutine f2pyinitwk_rela(setupfunc)
      external setupfunc
      real rr(2000)
      real rs(2000)
      common /wk_rela/ rr,rs
      call setupfunc(rr,rs)
      end

      subroutine f2pyinitcm16(setupfunc)
      external setupfunc
      real e1
      real e2
      integer ne
      integer ix
      integer neuo
      common /cm16/ e1,e2,ne,ix,neuo
      call setupfunc(e1,e2,ne,ix,neuo)
      end

      subroutine f2pyinitcmrv(setupfunc)
      external setupfunc
      real r(201)
      real v(201,15)
      integer nr
      integer nl
      real z
      common /cmrv/ r,v,nr,nl,z
      call setupfunc(r,v,nr,nl,z)
      end

      subroutine f2pyinitcm5(setupfunc)
      external setupfunc
      real y(30,4)
      real f(30,4)
      integer ilst
      common /cm5/ y,f,ilst
      call setupfunc(y,f,ilst)
      end

      subroutine f2pyinitzzzz(setupfunc)
      external setupfunc
      double precision zp(340)
      double precision vs
      integer ipt
      integer jri
      common /zzzz/ zp,vs,ipt,jri
      call setupfunc(zp,vs,ipt,jri)
      end

      subroutine f2pyinitz(setupfunc)
      external setupfunc
      double precision rmaxi
      common /z/ rmaxi
      call setupfunc(rmaxi)
      end

      subroutine f2pyinitradfun(setupfunc)
      external setupfunc
      double precision u(340)
      double precision w(340)
      common /radfun/ u,w
      call setupfunc(u,w)
      end
